### PR TITLE
add basic attachment support

### PR DESCRIPTION
**Pull request by LyricLy**

### CODE REVIEW

**Comment by LyricLy** [comment]
wait, hang on, this isn't quite right

**Comment by ihaveamac** [comment]
would be better to keep it in the same embed.

**Comment by LyricLy** [comment]
true. don't know where to put it, though

**Comment by LyricLy** [comment]
maybe as a seperate field

**Comment by LyricLy** [comment]
how's that?

**Comment by ihaveamac** [comment]
have you tested it?

**Comment by LyricLy** [comment]
no, not yet. will do so now

**Comment by LyricLy** [comment]
right, now it works

**Pull request merged**
